name: 'action-deploy-s3-cloudfront'
description: 'Publish on S3 and invalidate Cloudfront'

inputs:  
  aws-s3-bucket:
    required: true
    description: 'aws s3 bucket'
  aws-s3-region:
    required: true
    description: 'aws s3 region'
  source-dir:
    required: true
    description: 'source-dir'
  aws-cloudfront-distribution:
    required: true
    description: 'aws cloudfront distribution'
  aws-cloudfront-region:
    required: true
    description: 'aws cloudfront region'  
  aws-access-key-id:
    required: true
    description: 'aws access key id' 
  aws-secret-key:
    required: true
    description: 'aws secret key'     

runs:
  using: "composite"
  steps:          
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ inputs.aws-s3-bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }} 
        AWS_REGION: ${{ inputs.aws-s3-region }}
        SOURCE_DIR: ${{ inputs.source-dir }}
        
    - uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ inputs.aws-cloudfront-distribution }}
        PATHS: "/index.html" 
        AWS_REGION: ${{ inputs.aws-cloudfront-region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}          

branding:
  icon: 'aperture'
  color: 'blue'
